# Wayland - Qt5/Qt6
QT_QPA_PLATFORM=wayland

# Wayland - SDL2
SDL_VIDEODRIVER=wayland

# Wayland - Electron/Chromium apps
ELECTRON_OZONE_PLATFORM_HINT=wayland

# AMD GPU / video acceleration
LIBVA_DRIVER_NAME=radeonsi
VDPAU_DRIVER=radeonsi
