# MPD config - $XDG_CONFIG_HOME/.config/mpd/mpd.config
pid_file "$XDG_CONFIG_HOME/mpd/mpd.pid"
db_file "~/.config/mpd/mpd.db"
state_file "~/.local/state/mpd/state"
playlist_directory "~/Music/Playlists"
log_file "~/.local/state/mpd/mpd.log"

music_directory "~/Music"

audio_output {
        type	"pipewire"
        name	"PipeWire output"
        # Optional
        #target          "bluez_output.F4_9D_8A_B4_8D_37.1"
}

audio_output {
	type	"fifo"
	name	"cava_fifo"
	path	"/tmp/mpd.fifo"
	format	"44100:16:2"
}
